### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zzcqinag** [BaofengZan/DBNet-TensorRT#2]
when l run ./dbnet -s ,l get the error:
09/29/2020-09:45:12] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::286, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
Segmentation fault (core dumped)
how to solve this?thank you!

**Comment by BaofengZan** [comment]
Sorry for the late reply. Please use the new repo: https://github.com/wang-xinyu/tensorrtx/tree/master/dbnet
